### ISSUE TITLE
Kanban board for capstone.

### ISSUE THREAD

**Issue by muneebulrehman** [muneebulrehman/doctors-hub-backend#13]
Hi,
We are a team of three, @muneebulrehman , @sangwa7, @EzekielUtshudi. 
You can check the kanban board for this project [here](https://github.com/users/muneebulrehman/projects/1)
![image](https://user-images.githubusercontent.com/33268927/184088915-8ab4d6c7-e627-4c77-b454-8b6ef5b81276.png)

**Comment by MuriloRoque** [comment]
Hi @muneebulrehman, @sangwa7, @EzekielUtshudi,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
